# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

accCpp <- function(AM, nodeNames, index) {
    .Call('_ToPASeq_accCpp', PACKAGE = 'ToPASeq', AM, nodeNames, index)
}

betweenness <- function(g, V) {
    .Call('_ToPASeq_betweenness', PACKAGE = 'ToPASeq', g, V)
}

colMax <- function(X) {
    .Call('_ToPASeq_colMax', PACKAGE = 'ToPASeq', X)
}

colMin <- function(X) {
    .Call('_ToPASeq_colMin', PACKAGE = 'ToPASeq', X)
}

downstreamCpp <- function(AM, nodeNames, index) {
    .Call('_ToPASeq_downstreamCpp', PACKAGE = 'ToPASeq', AM, nodeNames, index)
}

